#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean specie
wclean thermophysicalProperties

wclean basic
wclean multicomponentThermo

wclean chemistryModel
wclean solidThermo

#------------------------------------------------------------------------------
