#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
makeType=${1:-libso}
set -x 

wclean ./thermophysicalTransportModel
wclean ./fluid
wclean ./solid
wclean ./fluidThermo
wclean ./fluidMulticomponentThermo
wclean ./phaseFluidThermo
wclean ./phaseFluidMulticomponentThermo
wclean ./phaseSolid
wclean ./coupledThermophysicalTransportModels


#------------------------------------------------------------------------------
