// create timers for single step 
scalar Time0, Time1,Time2,Time3,Time4,Time5, Time7, Time8, Time_pre;
Time0=0; Time1 = 0;Time2 = 0;Time3 = 0;Time4 = 0; Time5 = 0; Time7=0; Time8=0; Time_pre=0;

// variables for specific fields
scalar rhoTime, UTime, YEcalPropertiesTime, pTime, updatePropertiesTime, totalTime, total_preTime;
rhoTime=0; UTime=0; YEcalPropertiesTime=0; pTime=0; updatePropertiesTime=0; totalTime=0; total_preTime=0;
