#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
makeType=${1:-libso}
set -x 

# comment out all of this if want to keep obj. files of this ver. -----
 ./src/Allwclean

wclean ./applications/modules/multicomponentFluid
wclean ./applications/modules/DTLreactingFoam
# ----------------------------------------------------------------------

cd $FOAM_USER_LIBBIN

rm -rf libchemistryModel.so
rm -rf libcombustionModels.so
rm -rf libcoupledThermophysicalTransportModels.so
rm -rf libfluidMulticomponentThermophysicalTransportModels.so
rm -rf libfluidThermophysicalModels.so
rm -rf libfluidThermophysicalTransportModel.so
rm -rf libfluidThermoThermophysicalTransportModels.so
rm -rf libfvConstraints.so
rm -rf libfvModels.so
rm -rf libinterRegionFvModels.so
rm -rf libmulticomponentThermophysicalModels.so
rm -rf libphaseFluidMulticomponentThermophysicalTransportModels.so
rm -rf libphaseFluidThermophysicalTransportModels.so
rm -rf libphaseSolidThermophysicalTransportModels.so
rm -rf libradiationModels.so
rm -rf librotorDisk.so
rm -rf libsolidThermophysicalTransportModels.so
rm -rf libsolidThermo.so
rm -rf libspecie.so
rm -rf libspecieTransfer.so
rm -rf libthermophysicalProperties.so
rm -rf libthermophysicalTransportModel.so

rm -rf libDTLreactingFoam.so
rm -rf libmulticomponentFluid.so

cd - 

cd $FOAM_USER_APPBIN

rm -rf chemkinToFoam
rm -rf DTMchemkinToFoam
rm -rf FTMchemkinToFoam

cd - 
#------------------------------------------------------------------------------
